service: sls-boilerplate-http

frameworkVersion: '2'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: '20201221'
  runtime: ${file(./configs/aws/awsconfig.${self:provider.stage}.json):RUNTIME}
  region: ${file(./configs/aws/awsconfig.${self:provider.stage}.json):AWS_REGION}

custom:
  memorysize: ${file(./configs/aws/awsconfig.${self:provider.stage}.json):MEM_SIZE}
  timeout: ${file(./configs/aws/awsconfig.${self:provider.stage}.json):TIMEOUT}
  serverless-offline:
    httpPort: ${opt:port, 8080}

functions:
  root:
    handler:
      - middlewares/bodyparser.bodyparser
      - then: scripts/root.handler
    memorySize: ${self:custom.memorysize}
    timeout: ${self:custom.timeout}
    description: Hello World Template
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-middleware
  - serverless-offline
  - serverless-dotenv-plugin
